### ISSUE TITLE
没有大局，自私。

### ISSUE THREAD

**Issue by taohy** [995icu/996ICU#1]

**Comment by cqcpcqp** [comment]
> 又不止是程序员996而已，很多行业都是吧，以为程序员工资高，有点钱就乱跳了么。好不容易有个行业，能让农村大学生拼命就能往上爬，你们这些人是要把这个通道也堵死么。
> 对底层最不友好的，不是那些高高在上的资本家，而是刚脱离底层的那些人。看来这句话没说错啊。

sb 滚 写的狗屁

**Comment by a5467021** [comment]
噗 恭喜您老今年在github做出了第一份贡献

**Comment by AlvinMengCao** [comment]
所以就因为很多行业都这样，就觉得理所应当了是吗？等你35岁了没当上总监，被辞退了，因为年龄大了找不到IT工作，又因为身体不好干不了其他行业的时候，可能你才会体会到这个制度的可耻吧。哦对了， 可能在这之前你准备找对象结婚生小孩，也能提前感受到996的不便。

如果当初实行996大家都一直反对的话，就不会有公司会这么干。可是一旦有一个人或者一小撮人接受了996，这大厦就崩塌了。那些面对996保持沉默的人，虽然也叫苦不迭，但某种意义上也正是他们加剧了这种现象。

现在有人站出来用于发出自己的声音，希望通过法律维护自己的权益，却被你说成有钱乱蹦。。。。。。

**Comment by SineTitans** [comment]
有的人一边和工人兄弟姐妹们争抢资老爷们切完蛋糕留下的边角料，一边骂那些上桌抢蛋糕的人，说他们自私不顾大局，怕他们搞到老爷们不高兴了以后连边角料都不留。
这不就是鲁迅笔下向主子告状的长工么？
人家玩的就是囚徒困境，玩的就是二桃杀三士，却有人幼稚到以为安分守己就能换来蛋糕？
以斗争求团结，团结方能存！以战争回应战争，方能制止战争！
你以为资老爷很厉害么？你以为是资老爷出钱养你所以才该感恩么？恰恰相反，是工人付出了劳动养活了老爷们，却只得到了一点边角料而已！
尝试一次集体罢工，或者在相对重要岗位上尝试一次消极罢工，或者尝试一次炒老板鱿鱼，你就会明白，不是劳动者离不开资本家，反过来的逻辑才是正确的！

**Comment by Ayke** [comment]
Blame Marx for being selfish pls

**Comment by CatclysmSun** [comment]
这事要抨击就只能抨击政府了。一方面不限制人口增长导致人口过度富余工作岗位不够，明显不合理的工作岗位都很多人在抢。
另一方面政府劳动监察不作为，要是像其他国家那样企业要求员工超额加班重罚，还能有这么多逼事么？

至于指望所有人坚守底线不去996，醒醒吧。从20世纪初美铁华人劳工不参与罢工开始，这么多年有哪次国人能团结在一起坚守底线？
