### ISSUE TITLE
描述应该改成 单位不规范 亲人两行泪

### ISSUE THREAD

**Issue by AndersChen123** [995icu/996ICU#114]
加班没有规范的，改成“单位不规范 亲人两行泪”比较好。

**Comment by eddieqq1** [comment]
**聊天室 —— 没有自我审查**

**https://gitter.im/chinapolitics/Gate**

**TOR 浏览器 8.0.8 —— 绕过GFW**

![TOR 浏览器](https://raw.githubusercontent.com/mjstest/orgb1/fa270a800386564b0071bd8eb367b17d/2019-04-06_22-27-39.png?raw=true)

**https://chinagate.gitlab.io**
