### ISSUE TITLE
该996还是996，并没有争取到合法的权益

### ISSUE THREAD

**Issue by rover1024** [995icu/996ICU#171]
该996还是996，并没有争取到合法的权益 😭

**Comment by zqy233** [comment]
听说已存到北极，回来考古，同志们，总有一天会实现共产主义

**Comment by nany1999** [comment]
东野稷御马
东野稷以御见庄公，进退中绳，左右旋中规。庄公以为父弗过也，使之钩百而反。颜阖（读音hé）遇之，[入见](https://baike.baidu.com/item/%E5%85%A5%E8%A7%81/7222633)曰：“稷之马将败。”公默而不应。少焉，果败而反。公曰：“子何以知之？”曰：“其马力竭矣，而犹求焉，故曰败。”
译文[编辑](javascript:;)[ 播报](javascript:;)
东野稷凭驾驶马车的技术向庄公自荐，（他驾驶马车）前进、后退时（车轮压出的痕迹）都符合尺画的（一样笔直），左右拐弯（的车痕）都符合画出来的圆（一样圆）。庄公认为即使是造父也超不过他，就让他驾车按原印跑一百次再停下。颜阖碰见东野稷正在驾驶马车，就进入拜见庄公，道：“东野稷的马肯定要倒的。”庄公什么也没说。不久，（东野稷的马）果然翻过来倒下了。（这时）庄公（问颜阖）说：“你怎么知道他的马会倒？”（颜阖）回答说：“他的马的力气用完了，还要强行求全，所以说他会失败。”
