### ISSUE TITLE
我就想说 你这跟网上抵制半天不就是个自嗨么，一个个跟网上高潮。有点能耐找高层去解决处理啊，实际解决问题去。跟这自嗨有用么，不是SB么。

### ISSUE THREAD

**Issue by QiuHC** [995icu/996ICU#50]
我就想说 你这跟网上抵制半天不就是个自嗨么，一个个跟网上高潮。有点能耐找高层去解决处理啊，实际解决问题去。跟这自嗨有用么，不是SB么。

**Comment by marsemk** [comment]
那公民各种游行干啥 咋不直接去砸了政府呢

**Comment by huangwuzhao** [comment]
能不能解决是一回事，表明态度又是一回事。就是因为很多你这样的人，所以才让资本家觉得大家被压榨得很开心。

**Comment by dcshoecousa** [comment]
可以解决提问题的人(滑稽)

**Comment by yungfu** [comment]
高层是你想见就能见，没有群体事件，政府一般都不理你的。杭州的有赞，当时监管部门可表态了，不还是不了了之。
不过马上就是五一了，1886年芝加哥的工人已经带头争取了8小时工作制，恩格斯也为大家设立了五一劳动节嘛，不是正是合适的表达时机，来来来，穿上你们的白体恤，拿起马克笔，背上都写上NO 996，从中关村走到西长安，从国贸走到东长安去。
接着就是五四了，也值得出去走一走的。

对了去之前记得向公安局申请下，看会批准不会......

**Comment by duskwings** [comment]
还找高层？你在高层眼中不过是猪圈里的猪，还真以为自己有选择命运的机会了？太天真

**Comment by esvvv** [comment]
你有能耐就去找高层把github屏蔽了，实际解决问题去。跟这自嗨有用么，不是SB么。

**Comment by OJMars** [comment]
如果问题反馈了，高层就能知道，就可以着实解决，谁还来这里

**Comment by WaltCastiel** [comment]
找高层抵制只有一个结果，被炒。然后也许你会说，被炒就是你还不够优秀，公司随便就把你炒了.  不过绝大部分人在公司的眼里，都只是颗螺丝钉吧。 没办法可以替代性就是那么强，发发牢骚还不行了么

**Comment by geekstartup42** [comment]
按照你的意思，屁都不放

**Comment by sigui993** [comment]
我们不必去找高层是因为我们想解决的不是自己一个人或一家公司面临的问题我们要解决的是整个行业的不规范,兄弟只能说你自己眼界低了,只看得到自己一两个小时的加班,看不到这种环境对互联网产业,对社会劳动制度的破坏

**Comment by mikoyan25** [comment]
跪久了站不直系列？

**Comment by songdi676** [comment]
星星之火，可以燎原。共产党成立的时候也没有想到今天的天下都是共产党的。

**Comment by BeiJCSir** [comment]
实际上我上班不996，只是看到有点意思吐槽一下，没想到吐槽一下，还是有人回复啊。首先我不反对大家在网上自嗨，嗨完管用最好，不管用就当啊Q精神玩耍一番，该加班的加班。我所说的高层没有想象的那么高，你可以去找自己的领导反应啊，领导的领导应该也能说上话吧，难道你上班就见不到你们的领导去反映问题吗？ 后面有说星星之火可以燎原的那个哥们，如果当初有互联网，我党都在网上口嗨能建国那可就牛逼大了。

**Comment by BeiJCSir** [comment]
> 那公民各种游行干啥 咋不直接去砸了政府呢

游行是一种实际行动，网上自嗨也能当游行么？虽然会有一些影响，能比的上游行吗？付出的时间精力都不一样不要偷换概念。

**Comment by songdi676** [comment]
> 实际上我上班不996，只是看到有点意思吐槽一下，没想到吐槽一下，还是有人回复啊。首先我不反对大家在网上自嗨，嗨完管用最好，不管用就当啊Q精神玩耍一番，该加班的加班。我所说的高层没有想象的那么高，你可以去找自己的领导反应啊，领导的领导应该也能说上话吧，难道你上班就见不到你们的领导去反映问题吗？ 后面有说星星之火可以燎原的那个哥们，如果当初有互联网，我党都在网上口嗨能建国那可就牛逼大了。
【星星之火，可以燎原】：没说在网上发发帖子就能建国，兄弟不要断章取义。这句话的意思是，现在大家在网上发表看法（你的意思就是过过嘴瘾，自嗨），不代表一直在网上啊。事情会继续发展，可能一年也可能十年。现在媒体不都在报道了吗。事情不是一蹴而就。不要小看现在的渺小

**Comment by songdi676** [comment]
> 实际上我上班不996，只是看到有点意思吐槽一下，没想到吐槽一下，还是有人回复啊。首先我不反对大家在网上自嗨，嗨完管用最好，不管用就当啊Q精神玩耍一番，该加班的加班。我所说的高层没有想象的那么高，你可以去找自己的领导反应啊，领导的领导应该也能说上话吧，难道你上班就见不到你们的领导去反映问题吗？ 后面有说星星之火可以燎原的那个哥们，如果当初有互联网，我党都在网上口嗨能建国那可就牛逼大了。

>
【星星之火，可以燎原】：没说在网上发发帖子就能建国，兄弟不要断章取义。这句话的意思是，现在大家在网上发表看法（你的意思就是过过嘴瘾，自嗨），不代表一直在网上啊。事情会继续发展，可能一年也可能十年。现在媒体不都在报道了吗。事情不是一蹴而就。不要小看现在的渺小

**Comment by BeiJCSir** [comment]
> > 实际上我上班不996，只是看到有点意思吐槽一下，没想到吐槽一下，还是有人回复啊。首先我不反对大家在网上自嗨，嗨完管用最好，不管用就当啊Q精神玩耍一番，该加班的加班。我所说的高层没有想象的那么高，你可以去找自己的领导反应啊，领导的领导应该也能说上话吧，难道你上班就见不到你们的领导去反映问题吗？ 后面有说星星之火可以燎原的那个哥们，如果当初有互联网，我党都在网上口嗨能建国那可就牛逼大了。
> 
> > 
> 
> 【星星之火，可以燎原】：没说在网上发发帖子就能建国，兄弟不要断章取义。这句话的意思是，现在大家在网上发表看法（你的意思就是过过嘴瘾，自嗨），不代表一直在网上啊。事情会继续发展，可能一年也可能十年。现在媒体不都在报道了吗。事情不是一蹴而就。不要小看现在的渺小

理解

**Comment by BeiJCSir** [comment]
> 我就想说 你这跟网上抵制半天不就是个自嗨么，一个个跟网上高潮。有点能耐找高层去解决处理啊，实际解决问题去。跟这自嗨有用么，不是SB么。
