### ISSUE TITLE
为什么不选择反抗一下呢？

### ISSUE THREAD

**Issue by olocat** [995icu/996ICU#52]
我不太清楚为什么？但是大家的意思基本是只愿吐槽却不愿真的站出来
如果大家原意出来的话，各大公司的屏蔽又有什么用？
不如相约9月9日6点，大家选地点吧！
如果每个人都想着等待他人的成功，而为自己得利！那这无论何时，处境都不会变！！
今天他们敢屏蔽我们的主页，后天他们又干做什么？？
中国是社会主义国家，我不想信会让一群资本家控制住！！！

**Comment by hui305** [comment]
争取你个人的自由，就是争取国家的自由！

**Comment by hololalal** [comment]
被房价绑架了

**Comment by lettywiterock** [comment]
个人是没有能力反抗的,这个时候怕的也不应该普通打工者.
资本是无限膨胀的,只不过作为柴薪燃烧的是普通人罢了.
总有一天他们会不满足于现状,逼迫996,让普通人的仇恨转移,只是他们的开始.

**Comment by athenafirst** [comment]
很抱歉，目前996的公司列表里没有外企，资本主义表示这锅我们不背😂

**Comment by torchina** [comment]
**聊天室 - 没有自我审查**

**https://gitter.im/torchina/community**

**Tor 浏览器 8.0.8 - 绕过gfw**

![Tor Browser](https://github.com/torchina/get/blob/master/2019-04-06_22-27-39.png?raw=true)

**https://torchina.github.io/get**
