### ISSUE TITLE
刚在appstore发现个 “996,ICU” 的APP，大家可以在里面交流，不用担心被和谐了

### ISSUE THREAD

**Issue by superlangs** [995icu/996ICU#69]

**Comment by torchina** [comment]
聊天室 - 没有自我审查
https://gitter.im/torchina/community

Tor 浏览器 8.0.8 - 绕过gfw
https://torchina.github.io/get

**Comment by sam1129** [comment]
貌似没有找到安卓版本的

**Comment by elfgzp** [comment]
https://m.okjike.com/originalPosts/5cac1619168a92001841952d?username=C8A12852-6EDD-4E56-855E-BFD785681462
别上当
