### ISSUE TITLE
这不只是劳方与资方利益的争斗，也是价值观的辩驳

### ISSUE THREAD

**Issue by l523402485** [995icu/996ICU#93]
996=努力奋斗追求人生理想？
965=不思进取贪图安逸享乐？

**Comment by amateratu** [comment]
是996绝不可常态化，不然大家都干996的活，仍然拿原本的工资

权益是在退缩中失去的，前途是在不知不觉中断送的。。。

中国的人民，压力已经世界最勤劳，不能再继续逼了。。。
