### ISSUE TITLE
矫情的程序员

### ISSUE THREAD

**Issue by pki-sjin** [995icu/996ICU#99]
不知道这个repo的存在的意义是什么，诉苦吗？还是对工作的不满，相比其他行业程序员已经算不错的了，体面的办公环境，不菲的经济收入，工作强度来说996算强吗？看看其他行业呢，医院，餐饮，服务类行业哪个不比程序员累，辛苦，收入远远跟不上程序员。996怎么了？没有给足加班费吗？没有提供加班餐吗？没有给你们带薪病假和年假吗？如果都给了，叫唤什么？
马云说996是福气，说的对，给了业内顶级的薪资的福利，不是谁都有资格996的。
针对那些无偿996的公司，程序员你大可以换工作换公司，大把的好公司好工作等着你，这里发什么牢骚，真丢人。

**Comment by ZJH9Rondo** [comment]
你说你妈呢？你见过哪个行业猝死率有程序员高？996不是最关键的，程序员久坐+不停的解决问题+压力，身体质量越来越差，医院的主治医师的996和研究+程序员的996完全是两个概念，不是单纯从时间算得

**Comment by pki-sjin** [comment]
> 你说你妈呢？你见过哪个行业猝死率有程序员高？996不是最关键的，程序员久坐+不停的解决问题+压力，身体质量越来越差，医院的主治医师的996和研究+程序员的996完全是两个概念，不是单纯从时间算得

那你是没有关注其他行业，久坐难道就不能隔一段时间多动动，有些事情自己都是可以去克服的，手术医生一台重大手术一做就是几个小时甚至十几个小时，一个手术室的人陪着，再加上医患纠纷，医闹等等，程序员猝死完全可以自己掌控和避免，医生被医闹分子迫害比起程序员莫名其妙猝死来说哪个更让人觉得惋惜？

**Comment by ZJH9Rondo** [comment]
跟你说也是白说

**Comment by 460784634** [comment]
如果争取法律规定下的权利也是矫情的话,那真的是无话可说
我愿意奋斗,但我也想要我自己在法律规定下的权利
这次只是程序员说出来了
任何行业都可以去争取法律规定下的权利
当然你也可以不争取
但请不要以各种奋斗鸡汤讽刺别人争取赢得的权利
针对于医生,他们的行业性质较为特殊,他们更受到人们的尊重
但这不是说他们就应该加班,应该出台响应的政策去调整医生的工作时间

**Comment by marjde** [comment]
**聊天室 —— 没有自我审查**

**https://gitter.im/chinapolitics/Gate**

**Comment by WisZhou** [comment]
先辈们流血争取来的全人类权利，不应因少数人利益或个人好恶轻易放弃，否则对大部分人不公平
薪资是供需关系决定的，而非其他。目前程序员收入是来自于企业与社会对该工种的需求。接受996会畸形增加供应，最终会压低行业平均薪资，劣币逐良
历史证明人类社会常会因一些个人或集团利益停滞或倒退，但最终将会向前，这也是人类得以兴盛的一大特性

**Comment by stonesis** [comment]
你怎么不拿程序员跟奴隶比呢，程序员要比奴隶好多了，程序员要知足，是不是啊？奴隶就是贱命一条。是不是资本家眼中把程序员变成奴隶就好了？把中国变成奴隶社会更好？

**Comment by thedog54** [comment]
**聊天室 —— 没有自我审查**

**https://gitter.im/chinapolitics/Gate**

**TOR 浏览器 8.0.8 —— 绕过GFW**

![TOR 浏览器](https://raw.githubusercontent.com/mjstest/orgb1/fa270a800386564b0071bd8eb367b17d/2019-04-06_22-27-39.png?raw=true)

**https://chinagate.gitlab.io**

**Comment by map612** [comment]
> > 你说你妈呢？你见过哪个行业猝死率有程序员高？996不是最关键的，程序员久坐+不停的解决问题+压力，身体质量越来越差，医院的主治医师的996和研究+程序员的996完全是两个概念，不是单纯从时间算得
> 
> 那你是没有关注其他行业，久坐难道就不能隔一段时间多动动，有些事情自己都是可以去克服的，手术医生一台重大手术一做就是几个小时甚至十几个小时，一个手术室的人陪着，再加上医患纠纷，医闹等等，程序员猝死完全可以自己掌控和避免，医生被医闹分子迫害比起程序员莫名其妙猝死来说哪个更让人觉得惋惜？

都是想活的好点而已，程序员坐着就起不来了，脑力劳动和但手熟耳的工作还是有差别的

**Comment by ygl-rg** [comment]
真尼玛搞笑,发牢骚有什么问题?

其他行业辛苦? 

他们辛苦不抱怨是他们的选择,关我什么事?
